pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    echo "--- BUILDING ---"
                    npm ci
                    npm run build
                '''
                // Stash the build artifacts to use in later stages
                stash name: 'build-artifacts', includes: 'build/**'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps {
                // Unstash the build artifacts
                unstash 'build-artifacts'
                
                sh '''
                    echo "--- TESTING ---"
                    test -f build/index.html
                    npm test
                '''
            }
        }
        stage('E2E') {
            agent {
                docker {
                    // Use the correct image version required by your Playwright dependency
                    image 'mcr.microsoft.com/playwright:v1.39.0-jammy'
                    reuseNode true
                }
            }
            steps {
                // Unstash the build artifacts so the server can find them
                unstash 'build-artifacts'

                sh '''
                    echo "--- E2E TESTING ---"
                    npm install serve
                    # Start the server in the background
                    node_modules/.bin/serve -s build &
                    # Wait for 10 seconds to ensure the server is ready
                    sleep 10
                    # Run the Playwright tests
                    npx playwright test
                '''
            }
        }
    }
    post {
        always {
            // Archive the test results generated by the 'Test' stage
            junit 'test-results/junit.xml'
        }
    }
}
