pipeline {
    agent any 

    environment {
        Node_Image = 'node:18-alpine'
        JestResults = 'jest-results/junit.xml'
        Play_Wright_Image= 'mcr.microsoft.com/playwright:v1.56.1-noble'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            agent {
                docker {
                    image "${Node_Image}"
                    reuseNode true
                }
            }
            steps {
                sh '''
                    ls -la
                    node --version
                    npm --version

                    # Install dependencies
                    npm ci

                    # Build the project
                    npm run build

                    ls -la
                '''
            }
            post {
                success {
                    archiveArtifacts artifacts: 'build/**', allowEmptyArchive: true
                }
            }
        }

        stage('Test') {
            agent {
                docker {
                    image "${Node_Image}"
                    reuseNode true
                }
            }
            steps {
                sh '''
                    # Ensure build file exists
                    test -f build/index.html

                    # Run tests
                    npm test
                '''
            }
        }

        stage('E2E') {
            agent {
                docker {
                    image "${Play_Wright_Image}"
                    reuseNode true
                }
            }
            steps {
                sh '''
                    npm install -g serve
                    serve -s build
                    npx playwright test
                '''
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
            junit 'jest-results/junit.xml'
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}


// Test Trigger - 5

/*

pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    echo "--- BUILDING ---"
                    npm ci
                    npm run build
                '''
                // Stash the build artifacts to use in later stages
                stash name: 'build-artifacts', includes: 'build/**'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps {
                // Unstash the build artifacts
                unstash 'build-artifacts'
                
                sh '''
                    echo "--- TESTING ---"
                    test -f build/index.html
                    npm test
                '''
            }
            post {
                always {
                    // Archive the test results generated by the 'Test' stage
                    junit 'jest-results/junit.xml'
                }
            }
        }
        stage('E2E') {
            agent {
                docker {
                    // Use the correct image version required by your Playwright dependency
                    image 'mcr.microsoft.com/playwright:v1.39.0-jammy'
                    reuseNode true
                }
            }
            steps {
                // Unstash the build artifacts so the server can find them
                unstash 'build-artifacts'

                sh '''
                    echo "--- E2E TESTING ---"
                    npm install serve
                    # Start the server in the background
                    node_modules/.bin/serve -s build &
                    # Wait for 10 seconds to ensure the server is ready
                    sleep 10
                    # Run the Playwright tests
                    npx playwright test --reporter=html
                '''
            }
            post {
                always {
                    // Archive the test results generated by the 'Test' stage
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, icon: '', keepAll: false, reportDir: 'playwright-report', reportFiles: 'index.html', reportName: 'Playwright HTML Report', reportTitles: '', useWrapperFileDirectly: true])
                }
            }
        }
    }
}

*/

